services:
  documents-api:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    command: node dist/main.js
    restart: always
    networks:
      - luis

  documents-worker:
    image: ${IMAGE_NAME}
    container_name: "${CONTAINER_NAME}-worker"
    command: node dist/main.worker.js
    restart: always
    networks:
      - luis

networks:
  luis:
    external: true