version: '3.8'

services:
  app:
    container_name: my-nestjs-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - PORT=8000
      - APP_URL=http://localhost:8000
      - CORS_ORIGIN=*