services:
  documents-services-production:
    build:
      context: .
      dockerfile: Dockerfile
    image: sysintegra-documents-image
    container_name: sysintegra-documents
    restart: always
    networks:
      - luis
    # ports:
      # - 6506:80

networks:
  luis:
    external: true