services:
  documents-services-production:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/syssoftintegra/documents:latest
    container_name: sysintegra-documents
    restart: always
    networks:
      - luis

networks:
  luis:
    external: true